=== gisuss/Taller-2---WEB/taller2.dtd
<!ELEMENT organizacion (cliente)+>
<!ELEMENT cliente (nombre, apellido, edad, genero, estado_civil, telefono+, correo+, direccion, profesion, ocupasion)>
	<!ATTLIST cliente cedula ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT estado_civil (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT profesion (#PCDATA)>
<!ELEMENT ocupasion (#PCDATA)>

=== gisuss/Taller-2---WEB/taller2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE organizacion SYSTEM "taller2.dtd">
<organizacion>
	<cliente cedula="20753800">
		<nombre>Jesus</nombre>
		<apellido>Romero</apellido>
		<edad>24</edad>
		<genero>Masculino</genero>
		<estado_civil>Soltero</estado_civil>
		<telefono>0424-4600000</telefono>
		<correo>gisuss8520@gmail.com</correo>
		<direccion>Urb. Parque Cabriales,    Naguanagua.</direccion>
		<profesion>Bachiller</profesion>
		<ocupacion>Estudiante</ocupacion>
	</cliente>
</organizacion>
